antora:
  extensions:
  - ./lib/antora/extensions/autoconfig-partial-build.js
  - ./lib/antora/extensions/inject-collector-config.js
  - '@antora/collector-extension'
  - ./lib/antora/extensions/version-fix.js
  - '@antora/atlas-extension'
  - '@opendevise/antora-release-line-extension'
site:
  title: Spring Security
  url: https://docs.spring.io/spring-security/reference
  robots: allow
git:
  ensure_git_suffix: false
content:
  sources:
  - url: https://github.com/spring-projects/spring-security
    branches: [main, '5.{{6..9},{1..9}+({0..9})}.x']
    tags: ['5.{{6..9},{1..9}+({0..9})}.+({0..9})?(-RC+({0..9}))', '6.+({0..9}).+({0..9})?(-{RC,M}*)']
    start_path: docs
asciidoc:
  attributes:
    page-pagination: ''
    hide-uri-scheme: '@'
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: httpd
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/latest/ui-bundle.zip
    snapshot: true
