site:
  title: Spring Security
  url: https://docs.spring.io/spring-security/reference
runtime:
  log:
    format: pretty
asciidoc:
  attributes:
    page-pagination: ''
content:
  sources:
    - url: https://github.com/spring-io/spring-generated-docs
      # NOTE: exclude 5.7.3 to demonstrate how to inject collector config
      branches:
      - 'spring-projects/spring-security/5.{{6..9},{1..9}+({0..9})}.{x,+({0..9})}'
      - '!spring-projects/spring-security/5.7.3'
    - url: https://github.com/spring-projects/spring-security
      branches: '5.{6..9}.x'
      tags: '5.{{6..9},{1..9}+({0..9})}.+({0..9})'
      start_path: docs
    # NOTE: use local repository for main to demonstrate running collector on worktree
    - url: ./..
      branches: HEAD
      start_path: docs
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: httpd
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/latest/ui-bundle.zip
    snapshot: true
antora:
  extensions:
    - ./antora/extensions/inject-collector-config.js
    - '@antora/collector-extension'
    - ./antora/extensions/version-fix.js
    - ./antora/extensions/major-minor-segment.js
