name: Rebuild Search Index
on:
  workflow_dispatch:
permissions: read-all
jobs:
  build:
    #if: github.repository_owner == 'spring-projects'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 5
    - name: Configure Indexer
      run: |
        CONFIG_FILE=.github/actions/docsearch-config.json
        curl -sL -o $CONFIG_FILE $(node -p "require('fs').readFileSync('antora-playbook.yml', 'utf8').match(/^  url: (.*)/m)[1]")/docsearch-config.json
        INDEX_NAME=$(node -p "JSON.parse(require('fs').readFileSync('$CONFIG_FILE')).index_name")
        echo "CONFIG_FILE=${CONFIG_FILE}" >> $GITHUB_ENV
        echo "INDEX_NAME_TMP=${INDEX_NAME}-${GITHUB_RUN_ID}" >> $GITHUB_ENV
    - name: Run Indexer
      uses: darrenjennings/algolia-docsearch-action@master
      with:
        algolia_application_id: ${{ secrets.ALGOLIA_APP_ID }}
        algolia_api_key: ${{ secrets.ALGOLIA_API_KEY }}
        file: ${{ env.CONFIG_FILE }}
